/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const getPinia: typeof import('@hlw-uni/mp-core')['getPinia']
  const hlw: typeof import('@hlw-uni/mp-core')['hlw']
  const http: typeof import('@hlw-uni/mp-core')['http']
  const nextTick: typeof import('vue')['nextTick']
  const onError: typeof import('@dcloudio/uni-app')['onError']
  const onHide: typeof import('@dcloudio/uni-app')['onHide']
  const onLaunch: typeof import('@dcloudio/uni-app')['onLaunch']
  const onLoad: typeof import('@dcloudio/uni-app')['onLoad']
  const onMounted: typeof import('vue')['onMounted']
  const onPageScroll: typeof import('@dcloudio/uni-app')['onPageScroll']
  const onPullDownRefresh: typeof import('@dcloudio/uni-app')['onPullDownRefresh']
  const onReachBottom: typeof import('@dcloudio/uni-app')['onReachBottom']
  const onReady: typeof import('@dcloudio/uni-app')['onReady']
  const onShareAppMessage: typeof import('@dcloudio/uni-app')['onShareAppMessage']
  const onShow: typeof import('@dcloudio/uni-app')['onShow']
  const onTabItemTap: typeof import('@dcloudio/uni-app')['onTabItemTap']
  const onUnload: typeof import('@dcloudio/uni-app')['onUnload']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const useApp: typeof import('@hlw-uni/mp-core')['useApp']
  const useAppStore: typeof import('@hlw-uni/mp-core')['useAppStore']
  const useDevice: typeof import('@hlw-uni/mp-core')['useDevice']
  const useLoading: typeof import('@hlw-uni/mp-core')['useLoading']
  const useMsg: typeof import('@hlw-uni/mp-core')['useMsg']
  const usePageMeta: typeof import('@hlw-uni/mp-core')['usePageMeta']
  const useRefs: typeof import('@hlw-uni/mp-core')['useRefs']
  const useRequest: typeof import('@hlw-uni/mp-core')['useRequest']
  const useUpload: typeof import('@hlw-uni/mp-core')['useUpload']
  const useUserStore: typeof import('@hlw-uni/mp-core')['useUserStore']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly getPinia: UnwrapRef<typeof import('@hlw-uni/mp-core')['getPinia']>
    readonly hlw: UnwrapRef<typeof import('@hlw-uni/mp-core')['hlw']>
    readonly http: UnwrapRef<typeof import('@hlw-uni/mp-core')['http']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onError: UnwrapRef<typeof import('@dcloudio/uni-app')['onError']>
    readonly onHide: UnwrapRef<typeof import('@dcloudio/uni-app')['onHide']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onLoad: UnwrapRef<typeof import('@dcloudio/uni-app')['onLoad']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onPageScroll: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageScroll']>
    readonly onPullDownRefresh: UnwrapRef<typeof import('@dcloudio/uni-app')['onPullDownRefresh']>
    readonly onReachBottom: UnwrapRef<typeof import('@dcloudio/uni-app')['onReachBottom']>
    readonly onReady: UnwrapRef<typeof import('@dcloudio/uni-app')['onReady']>
    readonly onShareAppMessage: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareAppMessage']>
    readonly onShow: UnwrapRef<typeof import('@dcloudio/uni-app')['onShow']>
    readonly onTabItemTap: UnwrapRef<typeof import('@dcloudio/uni-app')['onTabItemTap']>
    readonly onUnload: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnload']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly useApp: UnwrapRef<typeof import('@hlw-uni/mp-core')['useApp']>
    readonly useAppStore: UnwrapRef<typeof import('@hlw-uni/mp-core')['useAppStore']>
    readonly useDevice: UnwrapRef<typeof import('@hlw-uni/mp-core')['useDevice']>
    readonly useLoading: UnwrapRef<typeof import('@hlw-uni/mp-core')['useLoading']>
    readonly useMsg: UnwrapRef<typeof import('@hlw-uni/mp-core')['useMsg']>
    readonly usePageMeta: UnwrapRef<typeof import('@hlw-uni/mp-core')['usePageMeta']>
    readonly useRefs: UnwrapRef<typeof import('@hlw-uni/mp-core')['useRefs']>
    readonly useRequest: UnwrapRef<typeof import('@hlw-uni/mp-core')['useRequest']>
    readonly useUpload: UnwrapRef<typeof import('@hlw-uni/mp-core')['useUpload']>
    readonly useUserStore: UnwrapRef<typeof import('@hlw-uni/mp-core')['useUserStore']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
