/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const hlw: typeof import('@hlw-uni/mp-vue')['hlw']
  const http: typeof import('@hlw-uni/mp-vue')['http']
  const nextTick: typeof import('vue')['nextTick']
  const onError: typeof import('@dcloudio/uni-app')['onError']
  const onHide: typeof import('@dcloudio/uni-app')['onHide']
  const onLaunch: typeof import('@dcloudio/uni-app')['onLaunch']
  const onLoad: typeof import('@dcloudio/uni-app')['onLoad']
  const onMounted: typeof import('vue')['onMounted']
  const onPageScroll: typeof import('@dcloudio/uni-app')['onPageScroll']
  const onPullDownRefresh: typeof import('@dcloudio/uni-app')['onPullDownRefresh']
  const onReachBottom: typeof import('@dcloudio/uni-app')['onReachBottom']
  const onReady: typeof import('@dcloudio/uni-app')['onReady']
  const onShareAppMessage: typeof import('@dcloudio/uni-app')['onShareAppMessage']
  const onShareTimeline: typeof import('@dcloudio/uni-app')['onShareTimeline']
  const onShow: typeof import('@dcloudio/uni-app')['onShow']
  const onTabItemTap: typeof import('@dcloudio/uni-app')['onTabItemTap']
  const onUnload: typeof import('@dcloudio/uni-app')['onUnload']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const setupInterceptors: typeof import('@hlw-uni/mp-vue')['setupInterceptors']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const useApp: typeof import('@hlw-uni/mp-vue')['useApp']
  const useDevice: typeof import('@hlw-uni/mp-vue')['useDevice']
  const useLoading: typeof import('@hlw-uni/mp-vue')['useLoading']
  const useMsg: typeof import('@hlw-uni/mp-vue')['useMsg']
  const usePageMeta: typeof import('@hlw-uni/mp-vue')['usePageMeta']
  const useRefs: typeof import('@hlw-uni/mp-vue')['useRefs']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly hlw: UnwrapRef<typeof import('@hlw-uni/mp-vue')['hlw']>
    readonly http: UnwrapRef<typeof import('@hlw-uni/mp-vue')['http']>
    readonly onHide: UnwrapRef<typeof import('@dcloudio/uni-app')['onHide']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onShareAppMessage: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareAppMessage']>
    readonly onShareTimeline: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareTimeline']>
    readonly onShow: UnwrapRef<typeof import('@dcloudio/uni-app')['onShow']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly useMsg: UnwrapRef<typeof import('@hlw-uni/mp-vue')['useMsg']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
  }
}
